#created on: Dec 7, 2019
package cityrules

// list any import classes here.
import com.sample.Question;
import com.sample.ReadInput;
import com.sample.Main; 

import function com.sample.Utility.help;

// declare any global variables here
dialect "java"
      
rule "Hobby self birthing"
	when
		hobprof : Question(Question.Name == "hobProf", answer == HOBBY);
		birth : Question(Question.Name == "birth", answer == SELF);
	then
		System.out.println("You want to be a hobby herder who births themselves");
		help(drools,"info");
end

rule "Hobby other birthing"
	when
		hobprof : Question(Question.Name == "hobProf", answer == HOBBY);
		birth : Question(Question.Name == "birth", answer == OTHER);
	then
		System.out.println("You want to be a hobby herder who doesn't birth sheep themselves");
		help(drools,"info");
end

rule "Professional self birthing"
	when
		hobprof : Question(Question.Name == "hobProf", answer == PRO);
		birth : Question(Question.Name == "birth", answer == SELF);
	then
		System.out.println("You want to be a professional herder who births sheep themselves");
		help(drools,"info");
end

rule "Professional other birthing"
	when
		hobprof : Question(Question.Name == "hobProf", answer == PRO);
		birth : Question(Question.Name == "birth", answer == OTHER);
	then
		System.out.println("You want to be a professional herder and doesn't want to do birthing themselves.");
		help(drools,"info");
end

rule "No shed"
	when
		shed : Question(Question.Name == "hasShed", answer == NO);
		sheep : Question(Question.Name == "nSheep");
	then
		System.out.println("You should buy a shed. Since you want " + sheep.getAnswer() + " sheep your shed should be " + sheep.getAnswer() * 10 + " square meters big");
		help(drools,"info");
end

rule "Has shed"
	when
		shed : Question(Question.Name == "hasShed", answer == YES, status == UNUSED);
	then
		System.out.println("How big is your shed (in square meters)?");
		ReadInput.read("shedSize", Question.NUMB, shed.getKSession());
		
		help(drools,"info");
end

rule "Has land"
	when
	// status is a variable that's not yet used, but I thought it might be useful to have such a variable to prevent rules from firing twice...
		land : Question(Question.Name == "hasLand", answer == YES, status == UNUSED);
	then
		System.out.println("How big is your land (in acres)?");
		ReadInput.read("landSize", Question.NUMB, land.getKSession());
		
		help(drools,"info");
end

// To be profitable one needs to have at least 200 sheep and 70 acres of land (SO THIS SHOULD BE A RULE FOR PROFFESIONAL SHEEP HERDERS. For 200 sheep you need 70 acres of land
// 200/70 is 2.86 sheep/acre. 
rule "Has land and wants n sheep"
	when
		sheep : Question(Question.Name == "nSheep");
		land : Question(Question.Name == "landSize", answer < (sheep.getAnswer() * 2.85));
// Only talking about buying land. How much will leasing land cost rougly?
	then
		System.out.println("Buy or lease more land. Per acre you can hold roughly 3 sheep. Since you want " + sheep.getAnswer() + " sheep, and you have " + land.getAnswer() + 
		" acres of land, your need " + (sheep.getAnswer() * 2.85 - land.getAnswer()) + " acres more land.\n" +
		"An acre of land costs rougly 50.000€. Therefore you'll need " + ((sheep.getAnswer() * 2.85 - land.getAnswer()) * 50000) + "€ for buying land.\n" + 
		"Also one needs to keep in mind that 300€ entitlement (i.e. toeslagrechten) need to be paid per used acre of land. In your case this will cost you " + ((sheep.getAnswer() * 2.85 - land.getAnswer()) * 300) + "€");
		help(drools,"info");
end

// ALL THE FORMULAS IN HERE SHOULD PROBABLY BE MOVED TO A SEPARATE CLASS CALLED e.g. Cost.java 

rule "Has enough land and wants n sheep"
	when
		sheep : Question(Question.Name == "nSheep");
		land : Question(Question.Name == "landSize", answer >= (land.getAnswer() * 2.85));
	then
		System.out.println("You have enough land. Per acre you can hold roughly 3 sheep. Since you have " + land.getAnswer() + " acres, you could get " 
		+ ((land.getAnswer() - (sheep.getAnswer() * 2.85)) * 2.85)   + " more sheep");
		help(drools,"info");
end

// When you have more than 5 sheep you need to pay phosphate rights. Prices per sheep differ depending on slaugter, male, female, place and weight (non-slaugther lambs are free). Avg is roughly 90€ per sheep. HOW OFTEN??
rule "Phosphate rights"
	when
		sheep : Question(Question.Name == "nSheep", answer > 5);
	then
		System.out.println("When you have more than five sheep you'll need to pay (90€) phosphate rights per sheep. For " + sheep.getAnswer() + " this will cost " + (sheep.getAnswer() * 90) + "€ per ??");
		help(drools, "phosphate");  
end

// multiplying the amount of sheep times the shed size is arbitrary. Only during birthing (some) sheep need to be inside
rule "Has shed and wants n sheep"
	when
		sheep : Question(Question.Name == "nSheep");
		shedsize : Question(Question.Name == "shedSize", answer < sheep.getAnswer() * 10);
	then
		System.out.println("You should build another shed or expand your shed. Since you want " + sheep.getAnswer() + " sheep, and your shed is " + 
		shedsize.getAnswer() + " square meters, your shed should be " + (sheep.getAnswer() * 10 - shedsize.getAnswer()) + " square meters bigger");
		help(drools,"info");
end

// Why should people have a tractor? What are the alternatives? How much does a tractor cost exactly (https://edepot.wur.nl/429700)? 
rule "Has tractor"
	when
		tractor : Question(Question.Name == "hasTractor", answer == NO);
	then
		System.out.println("You should probably buy a tractor");
end

// In the end here there should probably be something of an overall advice. Total costs, is it a good idea to start this, when will you start making money, should you lease or buy land, etc.
rule "All good"
	when
		tractor : Question(Question.Name == "hasTractor", answer == YES);
		sheep : Question(Question.Name == "nSheep", answer > 200);
		land : Question(Question.Name == "landSize", answer >= (sheep.getAnswer() * 2.85));
		shedsize : Question(Question.Name == "shedSize", answer > (sheep.getAnswer() * 10));
	then
		System.out.println("You should be able to start a profitable sheep herding business");
end
		
		
		