#created on: Dec 30, 2019
package cityrules

// list any import classes here.
import com.sample.Model;
import com.sample.Fact;
import com.sample.Shed;
import com.sample.Materials;
import com.sample.Business;
import com.sample.Land;
import com.sample.Care;
import com.sample.Sheep;
import com.sample.Values;

import com.sample.Main; 
import function com.sample.Utility.help;
import function com.sample.ValueCalculations.*;

import function com.sample.Advice.*;

dialect "java"

rule "Phosphate"
	when
		$sheep : Sheep($totalNSheepWanted : totalNSheepWanted > 5, $costPhosphateRights : costPhosphateRights);
	then
		$sheep.setAdvice("When you have more than five sheep you'll need to pay (90 euros) phosphate rights per sheep. For " + 
		$totalNSheepWanted + " this will cost " + $costPhosphateRights + "euros per three years???");
end